version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/employee-management-system
    depends_on:
      - backend
    ports:
      - "80:80"

  backend:
    build:
      context: .
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: BhaRas@123
      DB_NAME: employee

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: BhaRas@123
      MYSQL_DATABASE: employee
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000" # Expose port 8080 on the host, proxying to port 80 in the container
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data:
